// Generated by gencpp from file grab/GrabServerRequest.msg
// DO NOT EDIT!


#ifndef GRAB_MESSAGE_GRABSERVERREQUEST_H
#define GRAB_MESSAGE_GRABSERVERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grab
{
template <class ContainerAllocator>
struct GrabServerRequest_
{
  typedef GrabServerRequest_<ContainerAllocator> Type;

  GrabServerRequest_()
    : state()  {
    }
  GrabServerRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::grab::GrabServerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grab::GrabServerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GrabServerRequest_

typedef ::grab::GrabServerRequest_<std::allocator<void> > GrabServerRequest;

typedef boost::shared_ptr< ::grab::GrabServerRequest > GrabServerRequestPtr;
typedef boost::shared_ptr< ::grab::GrabServerRequest const> GrabServerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grab::GrabServerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grab::GrabServerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grab::GrabServerRequest_<ContainerAllocator1> & lhs, const ::grab::GrabServerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grab::GrabServerRequest_<ContainerAllocator1> & lhs, const ::grab::GrabServerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grab

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::grab::GrabServerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grab::GrabServerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grab::GrabServerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grab::GrabServerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grab::GrabServerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grab::GrabServerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grab::GrabServerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::grab::GrabServerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf6d3a99f0fbeb66ULL;
  static const uint64_t static_value2 = 0xd3248fa4b3e675fbULL;
};

template<class ContainerAllocator>
struct DataType< ::grab::GrabServerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grab/GrabServerRequest";
  }

  static const char* value(const ::grab::GrabServerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grab::GrabServerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state\n"
"\n"
;
  }

  static const char* value(const ::grab::GrabServerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grab::GrabServerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GrabServerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grab::GrabServerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grab::GrabServerRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAB_MESSAGE_GRABSERVERREQUEST_H
