// Generated by gencpp from file grab/GrabServer.msg
// DO NOT EDIT!


#ifndef GRAB_MESSAGE_GRABSERVER_H
#define GRAB_MESSAGE_GRABSERVER_H

#include <ros/service_traits.h>


#include <grab/GrabServerRequest.h>
#include <grab/GrabServerResponse.h>


namespace grab
{

struct GrabServer
{

typedef GrabServerRequest Request;
typedef GrabServerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GrabServer
} // namespace grab


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grab::GrabServer > {
  static const char* value()
  {
    return "ba7d0f17aa81fce463f555ebbb18949e";
  }

  static const char* value(const ::grab::GrabServer&) { return value(); }
};

template<>
struct DataType< ::grab::GrabServer > {
  static const char* value()
  {
    return "grab/GrabServer";
  }

  static const char* value(const ::grab::GrabServer&) { return value(); }
};


// service_traits::MD5Sum< ::grab::GrabServerRequest> should match
// service_traits::MD5Sum< ::grab::GrabServer >
template<>
struct MD5Sum< ::grab::GrabServerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grab::GrabServer >::value();
  }
  static const char* value(const ::grab::GrabServerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grab::GrabServerRequest> should match
// service_traits::DataType< ::grab::GrabServer >
template<>
struct DataType< ::grab::GrabServerRequest>
{
  static const char* value()
  {
    return DataType< ::grab::GrabServer >::value();
  }
  static const char* value(const ::grab::GrabServerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grab::GrabServerResponse> should match
// service_traits::MD5Sum< ::grab::GrabServer >
template<>
struct MD5Sum< ::grab::GrabServerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grab::GrabServer >::value();
  }
  static const char* value(const ::grab::GrabServerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grab::GrabServerResponse> should match
// service_traits::DataType< ::grab::GrabServer >
template<>
struct DataType< ::grab::GrabServerResponse>
{
  static const char* value()
  {
    return DataType< ::grab::GrabServer >::value();
  }
  static const char* value(const ::grab::GrabServerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAB_MESSAGE_GRABSERVER_H
