// Generated by gencpp from file grab/GrabServerResponse.msg
// DO NOT EDIT!


#ifndef GRAB_MESSAGE_GRABSERVERRESPONSE_H
#define GRAB_MESSAGE_GRABSERVERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grab
{
template <class ContainerAllocator>
struct GrabServerResponse_
{
  typedef GrabServerResponse_<ContainerAllocator> Type;

  GrabServerResponse_()
    : success(false)  {
    }
  GrabServerResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::grab::GrabServerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grab::GrabServerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GrabServerResponse_

typedef ::grab::GrabServerResponse_<std::allocator<void> > GrabServerResponse;

typedef boost::shared_ptr< ::grab::GrabServerResponse > GrabServerResponsePtr;
typedef boost::shared_ptr< ::grab::GrabServerResponse const> GrabServerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grab::GrabServerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grab::GrabServerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grab::GrabServerResponse_<ContainerAllocator1> & lhs, const ::grab::GrabServerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grab::GrabServerResponse_<ContainerAllocator1> & lhs, const ::grab::GrabServerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grab

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::grab::GrabServerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grab::GrabServerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grab::GrabServerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grab::GrabServerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grab::GrabServerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grab::GrabServerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grab::GrabServerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::grab::GrabServerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::grab::GrabServerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grab/GrabServerResponse";
  }

  static const char* value(const ::grab::GrabServerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grab::GrabServerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::grab::GrabServerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grab::GrabServerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GrabServerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grab::GrabServerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grab::GrabServerResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAB_MESSAGE_GRABSERVERRESPONSE_H
